<a href="https://colab.research.google.com/github/atkhushboo/subscriber-churn-analysis-python/blob/main/fitly_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Fitly Data Analysis....

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
#import libraries ...

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
import os
os.listdir()

['.config', 'drive', 'sample_data']

In [5]:
# read CSV files.....

account_info = pd.read_csv("/content/drive/MyDrive/Fitly/da_fitly_account_info.csv")
customer_support = pd.read_csv("/content/drive/MyDrive/Fitly/da_fitly_customer_support.csv")
user_activity = pd.read_csv("/content/drive/MyDrive/Fitly/da_fitly_user_activity.csv")

In [6]:
# account info data view
account_info.head()

,customer_id,email,state,plan,plan_list_price,churn_status
0,C10000,user10000@example.com,New Jersey,Enterprise,105,Y
1,C10001,user10001@example.net,Louisiana,Basic,22,Y
2,C10002,user10002@example.net,Oklahoma,Basic,24,NaN
3,C10003,user10003@example.com,Michigan,Free,0,NaN
4,C10004,user10004@example.com,Texas,Enterprise,119,NaN

In [7]:
# Customer support data view
print(customer_support.head())

                  ticket_time  user_id channel      topic  \
0  2025-06-13 05:55:17.154573    10125    chat  technical
1  2025-08-06 13:21:54.539551    10109    chat    account
2  2025-08-22 12:39:35.718663    10149    chat  technical
3  2025-06-07 02:49:46.986055    10268   phone    account
4  2025-07-25 00:24:38.945079    10041   phone      other

   resolution_time_hours  state                          comments
0                  11.48      1                               NaN
1                   1.01      0                               NaN
2                  10.09      0  Erase my data from your systems.
3                   9.10      1                               NaN
4                   2.28      1                               NaN

In [8]:
# user activity data view

user_activity.head()

                   event_time  user_id     event_type
0  2025-09-08 15:05:39.422721    10118    watch_video
1  2025-09-08 08:15:05.264103    10220    watch_video
2  2025-11-14 06:28:35.207671    10009  share_workout
3  2025-08-20 16:53:38.682901    10227   read_article
4  2025-07-24 16:47:31.728422    10123  track_workout

In [9]:
# Data Size ......
print('account info:- ',account_info.shape)
print('customer support:- ',customer_support.shape)
print('user sctivity:- ',user_activity.shape)

account info:-  (400, 6)
customer support:-  (918, 7)
user sctivity:-  (445, 3)

In [10]:
# Basic INFOMATION of data
account_info.info()
print("-" * 50)

customer_support.info()
print("-" * 50)

user_activity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      400 non-null    object
 1   email            400 non-null    object
 2   state            400 non-null    object
 3   plan             400 non-null    object
 4   plan_list_price  400 non-null    int64
 5   churn_status     114 non-null    object
dtypes: int64(1), object(5)
memory usage: 18.9+ KB
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ticket_time            918 non-null    object
 1   user_id                918 non-null    int64
 2   channel                918 non-null    object
 3   topic                  918 non-null    object
 4   resolution_time_hours  918 non-null    float64
 5   state                  918 non-null    int64
 6   comments               46 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 50.3+ KB
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445 entries, 0 to 444
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   event_time  445 non-null    object
 1   user_id     445 non-null    int64
 2   event_type  445 non-null    object
dtypes: int64(1), object(2)
memory usage: 10.6+ KB

In [11]:
# dataset overview

account_info.describe(include='all')
customer_support.describe(include='all')
user_activity.describe(include='all')

                        event_time       user_id    event_type
count                          445    445.000000           445
unique                         445           NaN             4
top     2025-07-18 10:09:46.737631           NaN  read_article
freq                             1           NaN           125
mean                           NaN  10198.930337           NaN
std                            NaN    113.583807           NaN
min                            NaN  10000.000000           NaN
25%                            NaN  10110.000000           NaN
50%                            NaN  10197.000000           NaN
75%                            NaN  10294.000000           NaN
max                            NaN  10396.000000           NaN

In [12]:
# Missing Values Check
print("Account Info")
print(account_info.isnull().sum())

print("\nCustomer Support")
print(customer_support.isnull().sum())

print("\nUser Activity")
print(user_activity.isnull().sum())

Account Info
customer_id          0
email                0
state                0
plan                 0
plan_list_price      0
churn_status       286
dtype: int64

Customer Support
ticket_time                0
user_id                    0
channel                    0
topic                      0
resolution_time_hours      0
state                      0
comments                 872
dtype: int64

User Activity
event_time    0
user_id       0
event_type    0
dtype: int64

In [13]:
# Duplicate values check

print("Account Info:", account_info.duplicated().sum())

print("customer support:",customer_support.duplicated().sum())

print("user activity:", user_activity.duplicated().sum())

Account Info: 0
customer support: 0
user activity: 0

In [14]:
print(customer_support["ticket_time"])

0      2025-06-13 05:55:17.154573
1      2025-08-06 13:21:54.539551
2      2025-08-22 12:39:35.718663
3      2025-06-07 02:49:46.986055
4      2025-07-25 00:24:38.945079
                  ...
913    2025-06-05 23:09:46.282238
914    2025-08-19 11:03:30.765219
915    2025-08-07 13:17:13.090150
916    2025-07-06 11:28:27.421494
917    2025-11-28 17:25:17.874347
Name: ticket_time, Length: 918, dtype: object

In [15]:
print(user_activity['event_time'])

0      2025-09-08 15:05:39.422721
1      2025-09-08 08:15:05.264103
2      2025-11-14 06:28:35.207671
3      2025-08-20 16:53:38.682901
4      2025-07-24 16:47:31.728422
                  ...
440    2025-10-22 12:09:09.477660
441    2025-09-22 18:28:07.618295
442    2025-07-28 14:52:16.311955
443    2025-11-27 13:38:32.371575
444    2025-07-18 10:09:46.737631
Name: event_time, Length: 445, dtype: object

In [16]:
customer_support['ticket_time'] = pd.to_datetime(customer_support['ticket_time'])
print(customer_support['ticket_time'])

0     2025-06-13 05:55:17.154573
1     2025-08-06 13:21:54.539551
2     2025-08-22 12:39:35.718663
3     2025-06-07 02:49:46.986055
4     2025-07-25 00:24:38.945079
                 ...
913   2025-06-05 23:09:46.282238
914   2025-08-19 11:03:30.765219
915   2025-08-07 13:17:13.090150
916   2025-07-06 11:28:27.421494
917   2025-11-28 17:25:17.874347
Name: ticket_time, Length: 918, dtype: datetime64[ns]

In [17]:
user_activity['event_time']= pd.to_datetime(user_activity['event_time'])
print(user_activity['event_time'])

0     2025-09-08 15:05:39.422721
1     2025-09-08 08:15:05.264103
2     2025-11-14 06:28:35.207671
3     2025-08-20 16:53:38.682901
4     2025-07-24 16:47:31.728422
                 ...
440   2025-10-22 12:09:09.477660
441   2025-09-22 18:28:07.618295
442   2025-07-28 14:52:16.311955
443   2025-11-27 13:38:32.371575
444   2025-07-18 10:09:46.737631
Name: event_time, Length: 445, dtype: datetime64[ns]

In [18]:
print(account_info['churn_status'].value_counts(dropna=False))

churn_status
NaN    286
Y      114
Name: count, dtype: int64

In [25]:
# Create a new customer ID column by removing the 'C' prefix for merging datasets.
account_info['user_id'] = account_info['customer_id'].str.replace('C', '').astype(int)
account_info.head()

,customer_id,email,state,plan,plan_list_price,churn_status,customer_id_new,user_id
0,C10000,user10000@example.com,New Jersey,Enterprise,105,Y,10000,10000
1,C10001,user10001@example.net,Louisiana,Basic,22,Y,10001,10001
2,C10002,user10002@example.net,Oklahoma,Basic,24,NaN,10002,10002
3,C10003,user10003@example.com,Michigan,Free,0,NaN,10003,10003
4,C10004,user10004@example.com,Texas,Enterprise,119,NaN,10004,10004

In [27]:
# check Duplicate values
print("Account info duplicate records:- ",account_info['user_id'].duplicated().sum())
print("Customer support duplicate records: - ",customer_support['user_id'].duplicated().sum())
print("User activity duplicate records:- ",user_activity['user_id'].duplicated().sum())

Account info duplicate records:-  0
Customer support duplicate records: -  551
User activity duplicate records:-  199